// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.16.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@24.0.14_db0@0.3.2_eslint@9_fjsihgf6ny5hjmwdlo6khn5oea/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@0.3.5_vite@6.3.5_@types+node@24.0.14_jiti@2.4.2_lightningcss@1.30._6m3dfc3a63tc67f6b7bqnis35m/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}