// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.16.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@24.0.14_db0@0.3.2_eslint@9_fjsihgf6ny5hjmwdlo6khn5oea/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.16.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@24.0.14_db0@0.3.2_eslint@9_fjsihgf6ny5hjmwdlo6khn5oea/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.16.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@24.0.14_db0@0.3.2_eslint@9_fjsihgf6ny5hjmwdlo6khn5oea/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.16.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@24.0.14_db0@0.3.2_eslint@9_fjsihgf6ny5hjmwdlo6khn5oea/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.16.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@24.0.14_db0@0.3.2_eslint@9_fjsihgf6ny5hjmwdlo6khn5oea/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.16.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@24.0.14_db0@0.3.2_eslint@9_fjsihgf6ny5hjmwdlo6khn5oea/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.16.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@24.0.14_db0@0.3.2_eslint@9_fjsihgf6ny5hjmwdlo6khn5oea/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.16.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@24.0.14_db0@0.3.2_eslint@9_fjsihgf6ny5hjmwdlo6khn5oea/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.16.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@24.0.14_db0@0.3.2_eslint@9_fjsihgf6ny5hjmwdlo6khn5oea/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.16.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@24.0.14_db0@0.3.2_eslint@9_fjsihgf6ny5hjmwdlo6khn5oea/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@2.6.2_vite@6.3.5_@types+node@24.0.14_jiti@2.4.2_lightningcss@1.30.1_sass-embed_2cflbo2ky43cpxb55mn6jbqr2a/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@2.6.2_vite@6.3.5_@types+node@24.0.14_jiti@2.4.2_lightningcss@1.30.1_sass-embed_2cflbo2ky43cpxb55mn6jbqr2a/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_@netlify+blobs@9.1.2_db0@0.3.2_embla-carousel@8.6.0_iored_hrdszvhzd42o35hxh7jxykj7ba/node_modules/@nuxt/ui/dist/runtime/plugins/colors.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.3.5/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.3.5/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@0.3.5_vite@6.3.5_@types+node@24.0.14_jiti@2.4.2_lightningcss@1.30._6m3dfc3a63tc67f6b7bqnis35m/node_modules/@nuxt/icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.16.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@24.0.14_db0@0.3.2_eslint@9_fjsihgf6ny5hjmwdlo6khn5oea/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.16.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@24.0.14_db0@0.3.2_eslint@9_fjsihgf6ny5hjmwdlo6khn5oea/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:browser-devtools-timing' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | '@nuxt/icon' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
