services:
  postgres:
    container_name: notify-postgres
    image: postgres:15
    environment:
      POSTGRES_USER: notifyuser
      POSTGRES_PASSWORD: notifypassword
      POSTGRES_DB: notify
    ports:
      - "5433:5432"  # Changed to port 5433 on host to avoid conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notifyuser -d notify"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data:
    name: notify-postgres-data
