name: Status API CI

on:
  pull_request:
    paths:
      - "status-api/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./status-api

jobs:
  status-api-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "status-api"
      working_directory: "./status-api"
      codecov_flag: "statusapi"