name: "[TEST] pnpm v11 upgrade"

on:
  push:
    branches: ["test/pnpm-v11-upgrade"]
  workflow_dispatch:

  pull_request:
    branches: [main]
    paths:
      - "document-service/documents-ui/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./document-service/documents-ui
jobs:
  documents-ui-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/frontend-ci.yaml@feat/upgrade-pnpm-v11
    with:
      pnpm_version: 'latest-11'
      app_name: "documents-ui"
      working_directory: "./document-service/documents-ui"
      codecov_flag: "documentsui"
      node_version: "24"
